version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - MONGODB_URI=mongodb://mongo:27017/arrasta_db
      - BASE_URL=http://localhost:8888
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: