name: Deploy Firebase Functions

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual triggers

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Install Firebase functions dependencies
      working-directory: ./functions
      run: npm ci

    - name: Lint Firebase functions
      working-directory: ./functions
      run: npm run lint

    - name: Deploy Firebase Functions
      env:
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        GOOGLE_APPLICATION_CREDENTIALS: ./service-account-key.json
      run: |
        echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > service-account-key.json
        firebase deploy --only functions --project arrasta-click

    - name: Set up cleanup policy for function artifacts
      env:
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        GOOGLE_APPLICATION_CREDENTIALS: ./service-account-key.json
      run: |
        firebase functions:artifacts:setpolicy --project arrasta-click