name: Deploy Firebase Functions

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual triggers

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Install Firebase functions dependencies
      run: |
        cd functions
        npm ci

    - name: Lint Firebase functions
      run: |
        cd functions
        npm run lint

    - name: Authenticate with Firebase
      run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > $HOME/service-account.json

    - name: Deploy Firebase Functions
      run: firebase deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/service-account.json